### ISSUE TITLE
detect_dual_tracking.py

### ISSUE THREAD

**Issue by ElijahBiocinth** [MuhammadMoinFaisal/YOLOv9-DeepSORT-Object-Tracking#2]
I can't find the cause of the error - the code is written quite clearly. Could you help me?

detect_dual_tracking: weights=['/home/jovyan/YOLO/runs/segment/train/weights/best.pt'], source=/home/jovyan/animation_with_interpolation.gif, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=0, view_img=False, nosave=False, draw_trails=True, classes=[0], agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, half=False, dnn=False, vid_stride=1
YOLO 🚀 83fbbcc Python-3.10.11 torch-2.2.0+cu121 CUDA:0 (Tesla V100-PCIE-32GB, 32501MiB)

YOLOv9c-seg summary (fused): 411 layers, 27626070 parameters, 0 gradients, 157.6 GFLOPs
Traceback (most recent call last):
  File "/home/jovyan/YOLOv9_track/YOLOv9-DeepSORT-Object-Tracking/detect_dual_tracking.py", line 319, in <module>
    main(opt)
  File "/home/jovyan/YOLOv9_track/YOLOv9-DeepSORT-Object-Tracking/detect_dual_tracking.py", line 313, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/jovyan/YOLOv9_track/YOLOv9-DeepSORT-Object-Tracking/detect_dual_tracking.py", line 191, in run
    pred = pred[0][1]
IndexError: index 1 is out of bounds for dimension 0 with size 1

**Comment by Hari-Mutyam** [comment]
I've got same issue @ElijahBiocinth  while I'm testing with another models but not yolov9-c.pt
